- name: Get cluster nodes
  command: kubectl get nodes
  become_user: "{{ ansible_user }}"
  delegate_to: "{{ groups['control_planes'][0] }}"
  register: get_nodes
  changed_when: false

- name: Check cluster nodes
  set_fact:
    joined: "{{ hostname }} is search(get_nodes.stdout)"

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['control_planes'][0] }}"
  when: not joined

- name: Set join_cmd variable
  set_fact:
    join_cmd: "{{ join_command.stdout }}"
  when: not joined

- name: Join the cluster
  command: "{{ join_cmd }}"
  when: not joined
