apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.5.1
      helm:
        valueFiles:
          - $values/infra/applications/longhorn/values.yaml
    - repoURL: https://github.com/SamiHonkasalo/homelab.git
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
