server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: vault.192.168.0.240.nip.io

ui:
  enabled: true
  serviceType: LoadBalancer
  annotations:
    argocd.argoproj.io/skip-health-check: "true"
