apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.25.0
      helm:
        valueFiles:
          - $values/infra/applications/vault/values.yaml
    - repoURL: https://github.com/SamiHonkasalo/homelab.git
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
