apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    chart: kubernetes-dashboard
    repoURL: https://github.com/SamiHonkasalo/homelab.git
    path: infra/applications
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
