- name: Check if control plane is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: check_init

- name: Set initialized variable
  set_fact:
    initialized: "{{ check_init.stat.exists | default(false) }}"

- name: Set is_first_host variable
  set_fact:
    is_first_host: inventory_hostname == groups['control_planes'][0]

- name: Initialize the control plane
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: not initialized and is_first_host # Initialize only on one control plane

- name: Create .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory

- name: Copy kubeconfig to user directory
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: true
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
  when: not initialized and is_first_host

- name: Wait for pods to wake
  pause:
    seconds: 30
  when: not initialized and is_first_host

- name: Install flannel
  become_user: "{{ ansible_user }}"
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: not initialized and is_first_host

- name: Wait for flannel and other pods to be ready
  pause:
    seconds: 30
  when: not initialized and is_first_host
# TODO:
# Install MetalLB
# For non-first control planes
# Get the join command from the first control plane and join the cluster as control planes
